### ISSUE TITLE
Keine Kompatibilität mit Contao 4.9?

### ISSUE THREAD

**Issue by freiwild** [Ma3xl3/Contao-EasyFavicon#11]
Nach Installation über den Contao Manager erscheint nicht wie gewohnt die Sektion "Favicon" in den Einstellungen der Webseiten-Startpunkts.

**Comment by theDyingMountain** [comment]
Ich habe gerade das gleiche Problem...

**Comment by Ma3xl3** [comment]
Hoffe ich komme demnächst dazu mir das Problem anzusehen.
Ist leider Aufgrund der aktuellen Situation etwas chaotisch.

**Comment by PaoloB** [comment]
I confirm, even I do not see the field to select the FavIcon.
There is a native function in 4.9, that could be the cause.

I hope you can verify the problem soon.
Thank you

**Comment by theDyingMountain** [comment]
Habe herausgefunden, dass es am neuen Seitentyp rootfallback liegt. Wenn ich den Sprachen Fallback deaktiviere, erscheinen die Favicon Einstellungen. Beim Aktivieren sind sie wieder weg. Habe allerdings noch keine Lösung.

**Comment by Aybee** [comment]
Push 😁

**Comment by Ma3xl3** [comment]
Sorry für die späte Umsetzung. 
Die Kompatibilität zu Contao 4.9 sollte in der 2.0.2 wieder hergestellt sein.
Wie @theDyingMountain erwähnte hängt es mit dem rootfallback zusammen.
Bitte um Feedback :)

**Comment by Aybee** [comment]
Contao 4.9.3

Jetzt sehe ich die Favicon-Einstellung wieder. Vielen Dank.
