### ISSUE TITLE
Kompatibilität Contao 4.13 public Root Ordner

### ISSUE THREAD

**Issue by 9teufel** [Ma3xl3/Contao-EasyFavicon#14]
Nutzt man in Contao 4.13 den public statt web Ordner als Root, so wird das Favicon trotzdem in web/share abgelegt und ist dann natürlich nicht erreichbar.

Das Apple Touch Icon wird richtig in public/share gespeichert.

**Comment by Ma3xl3** [comment]
Problem sollte in der 2.0.6 behoben sein.
Bitte nochmals prüfen.
