### ISSUE TITLE
Falsches Verzeichnis voreingestellt

### ISSUE THREAD

**Issue by swisschris** [Ma3xl3/Contao-EasyFavicon#3]
In einigen Websites habe ich das Phänomen, dass beim Wählen des Files, das für Favicon/Touch Icon verwendet werden soll, die Ansicht auf ein Verzeichnis (Knoten) eingeschränkt ist und nicht geändert werden kann. Jeder Klick in den gelben Balken auf «Alle» oder auf einen anderen Knotenpunkt zeigt keine Wirkung.

**Comment by Ma3xl3** [comment]
Was für eine Contao Version verwendest du?
Kann ich dieses Phänomen in der Contao-Demo Version irgendwie nachvollziehen.

**Comment by swisschris** [comment]
Das Phänomen tritt in verschiedenen Contao-Installationen und -Versionen auf: 3.5.0 / 3.3.3 / 3.2.14
Ich hätte gerne in der Contao-Demo deine Erweiterungen installiert, habe aber nicht herausgefunden, wie das funktionieren könnte.

Aber ich denke, ich habe das Rätsel eingrenzen können. 
1. Ich möchte einem Textelement ein Bild hinzufügen
> Bild hinzufügen > Auswahl ändern > [Klick auf Verzeichnisname] (nur diesen Knoten anzeigen)…
2. Ich möchte ein Favicon/Apple Touch Icon festlegen
> Seitenstruktur > [entsprechende Root-Seite bearbeiten] > Favicon hinzufügen > [Favicon Quelldatei] Auswahl ändern
Der zuvor gewählte Knoten bleibt und lässt sich über die Favicon-Dateiauswahl nicht verändern.

Wir haben das Problem nun gelöst, indem wir den Knoten über einen Nicht-Favicon-Bereich auflösen  und das Favicon zuweisen konnten.
