### ISSUE TITLE
Kompatibilität mit aktuellen Contao-Versionen

### ISSUE THREAD

**Issue by Schmidty2** [Ma3xl3/Contao-EasyFavicon#6]
Hallo,
kann die kompatibilität für Contao >=3.5.25 und Contao 4.3.x bzw. 4.4.x angepasst werden.
Danke.

**Comment by Ma3xl3** [comment]
Hallo Schmidty2.
Ich hoffe ich komme demnächst einmal dazu (der Faktor Zeit spielt mir hier einen Streich ;) ). Geplant wäre es nachdem die Contao LTS 4.4 erschienen ist.
Beste Grüße

**Comment by Ma3xl3** [comment]
EasyFavicon ist ab sofort für die 4.4 verfügbar. Hoffe es klapp soweit alles.
