### ISSUE TITLE
Apple Touch Icon greift nicht

### ISSUE THREAD

**Issue by designpilot** [Ma3xl3/Contao-EasyFavicon#7]
Ich habe bei einer Contao 4.4.7 die Extension von Dir installiert, das Favicon (habe dort ein PNG ausgewählt) greift ohne Problem, nur wenn ich das Apple Touch Icon festlegen möchte, kann ich zwar auch ein PNG auswählen 192x192 (wird ja eh auf 152x152 runter scaliert) nur wenn ich dann auf meinem iPhone X die Seite zum Homebildschirm hinzufügen will, wird dann einfach ein kleiner Ausschnitt der aktuellen Seite genommen auf der ich mich gerade befinde und nicht das festgelegte Apple Touch Icon.

Ich habe auch schon andere Seiten getestet und bei denen funktioniert es bestens. Kann es sein weil ich die Testseite in einer Subdomain habe das es aus diesem Grund nicht greift???? Wobei dann dürfte das Favicon auf nicht greifen.

**Comment by Ma3xl3** [comment]
Ich kann dein Problem leider nicht nachvollziehen. Ich habe es bei mir auf dem iPhone X Simulator probiert und es funktioniert. Eventuell die Favicons im web/share Ordner nochmals löschen.

Ist die Testseite online erreichbar?

**Comment by designpilot** [comment]
Hi

Ja die Seite wäre online erreichbar unter https://nakedfacts.designpilot.ch
Ich hab die Erweiterung nochmal deinstalliert und wieder installiert die
beiden Dateien aus dem web/share Ordner gelöscht hat aber auch nichts
genützt.



Mit freundlichen Grüssen
Didier Federer



Mattfeldstrasse 6 | CH-9532 Rickenbach bei Wil
Telefon: +41 76 514 39 55 | Mail: info@designpilot.ch <mailto:info@designpilot.ch>

**Comment by Ma3xl3** [comment]
Bei deiner Seite funktioniert es bei mir auch nicht. Eventuell liegt es am ungültigen Zertifikat. Kannst du die Seite über http auch freischalten und es nochmals probieren?

**Comment by designpilot** [comment]
Hi

Ah dann liegt es an dem wegen dem Zertifikat. Ich werd das dann sowieso umstellen dann weiss ich jetzt aber zumindest woran das es liegt.

Danke für die Hilfe und den Denkanstoss

Grüsse aus der nahen Schweiz
Didier

**Comment by Ma3xl3** [comment]
Super. Gib mir noch kurz Bescheid ob dies das Problem war.
Ich schließe derweil das Ticket.

**Comment by designpilot** [comment]
Sobald ich das ganze produktiv schalten kann werd ich das machen
